pipleline {
    agent any
    stages {
        stage("Server Details") {
            steps {
                echo "server details"
            }
        }
        stage("CPU Details") {
            steps {
                sh 'lscpu'
            }
        }
        stage("Memory Details") {
            steps {
                sh 'free -h'
            }
        }
        stage("Disk Details") {
            steps {
                sh 'df -h'
            }
        }
        stage("Network Details") {
            steps {
                sh 'ifconfig'
            }
        }
        stage("IP Address Details") {
            steps {
                sh 'hostname -i'
            }
        }
    }
}
