pipleline{
    agent any
    stages{
        stage("Server Details"){
            steps{
                echo "server details"
            }
        }
        stage("CPU Details"){
            steps{
                sh 'lscpu'
            }
        }
        stages("Memory Details"){
            steps{
                sh 'free -h'
            }
        }
        stage("Disk Details"){
            steps{
                sh 'df -h'
            }
        }
        stage("Network Details"){
            step{
                sh 'ifconfig'
            }
        }
        stage("IP Address Details"){
            steps{
                sh 'hostname -i'
            }
        }
    }
}
